FROM python:3.12-slim

WORKDIR /app

COPY requirements.celery.txt .
RUN pip install --no-cache-dir -r requirements.celery.txt

COPY . .

CMD ["celery", "-A", "src.core.celery.celery_app", "worker", "--loglevel=info", "--concurrency=4"]
