/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ColobusRouteRouteImport } from './routes/colobus/route'
import { Route as BuffaloRouteRouteImport } from './routes/buffalo/route'
import { Route as AkwaabaRouteRouteImport } from './routes/akwaaba/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColobusIndexRouteImport } from './routes/colobus/index'
import { Route as BuffaloIndexRouteImport } from './routes/buffalo/index'
import { Route as AkwaabaIndexRouteImport } from './routes/akwaaba/index'
import { Route as ColobusCurrentYearPlantingRouteImport } from './routes/colobus/current-year-planting'
import { Route as BuffaloCurrentYearPlantingRouteImport } from './routes/buffalo/current-year-planting'
import { Route as AkwaabaCurrentYearPlantingRouteImport } from './routes/akwaaba/current-year-planting'

const ColobusRouteRoute = ColobusRouteRouteImport.update({
  id: '/colobus',
  path: '/colobus',
  getParentRoute: () => rootRouteImport,
} as any)
const BuffaloRouteRoute = BuffaloRouteRouteImport.update({
  id: '/buffalo',
  path: '/buffalo',
  getParentRoute: () => rootRouteImport,
} as any)
const AkwaabaRouteRoute = AkwaabaRouteRouteImport.update({
  id: '/akwaaba',
  path: '/akwaaba',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColobusIndexRoute = ColobusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ColobusRouteRoute,
} as any)
const BuffaloIndexRoute = BuffaloIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuffaloRouteRoute,
} as any)
const AkwaabaIndexRoute = AkwaabaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AkwaabaRouteRoute,
} as any)
const ColobusCurrentYearPlantingRoute =
  ColobusCurrentYearPlantingRouteImport.update({
    id: '/current-year-planting',
    path: '/current-year-planting',
    getParentRoute: () => ColobusRouteRoute,
  } as any)
const BuffaloCurrentYearPlantingRoute =
  BuffaloCurrentYearPlantingRouteImport.update({
    id: '/current-year-planting',
    path: '/current-year-planting',
    getParentRoute: () => BuffaloRouteRoute,
  } as any)
const AkwaabaCurrentYearPlantingRoute =
  AkwaabaCurrentYearPlantingRouteImport.update({
    id: '/current-year-planting',
    path: '/current-year-planting',
    getParentRoute: () => AkwaabaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akwaaba': typeof AkwaabaRouteRouteWithChildren
  '/buffalo': typeof BuffaloRouteRouteWithChildren
  '/colobus': typeof ColobusRouteRouteWithChildren
  '/akwaaba/current-year-planting': typeof AkwaabaCurrentYearPlantingRoute
  '/buffalo/current-year-planting': typeof BuffaloCurrentYearPlantingRoute
  '/colobus/current-year-planting': typeof ColobusCurrentYearPlantingRoute
  '/akwaaba/': typeof AkwaabaIndexRoute
  '/buffalo/': typeof BuffaloIndexRoute
  '/colobus/': typeof ColobusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akwaaba/current-year-planting': typeof AkwaabaCurrentYearPlantingRoute
  '/buffalo/current-year-planting': typeof BuffaloCurrentYearPlantingRoute
  '/colobus/current-year-planting': typeof ColobusCurrentYearPlantingRoute
  '/akwaaba': typeof AkwaabaIndexRoute
  '/buffalo': typeof BuffaloIndexRoute
  '/colobus': typeof ColobusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akwaaba': typeof AkwaabaRouteRouteWithChildren
  '/buffalo': typeof BuffaloRouteRouteWithChildren
  '/colobus': typeof ColobusRouteRouteWithChildren
  '/akwaaba/current-year-planting': typeof AkwaabaCurrentYearPlantingRoute
  '/buffalo/current-year-planting': typeof BuffaloCurrentYearPlantingRoute
  '/colobus/current-year-planting': typeof ColobusCurrentYearPlantingRoute
  '/akwaaba/': typeof AkwaabaIndexRoute
  '/buffalo/': typeof BuffaloIndexRoute
  '/colobus/': typeof ColobusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/akwaaba'
    | '/buffalo'
    | '/colobus'
    | '/akwaaba/current-year-planting'
    | '/buffalo/current-year-planting'
    | '/colobus/current-year-planting'
    | '/akwaaba/'
    | '/buffalo/'
    | '/colobus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/akwaaba/current-year-planting'
    | '/buffalo/current-year-planting'
    | '/colobus/current-year-planting'
    | '/akwaaba'
    | '/buffalo'
    | '/colobus'
  id:
    | '__root__'
    | '/'
    | '/akwaaba'
    | '/buffalo'
    | '/colobus'
    | '/akwaaba/current-year-planting'
    | '/buffalo/current-year-planting'
    | '/colobus/current-year-planting'
    | '/akwaaba/'
    | '/buffalo/'
    | '/colobus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkwaabaRouteRoute: typeof AkwaabaRouteRouteWithChildren
  BuffaloRouteRoute: typeof BuffaloRouteRouteWithChildren
  ColobusRouteRoute: typeof ColobusRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/colobus': {
      id: '/colobus'
      path: '/colobus'
      fullPath: '/colobus'
      preLoaderRoute: typeof ColobusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buffalo': {
      id: '/buffalo'
      path: '/buffalo'
      fullPath: '/buffalo'
      preLoaderRoute: typeof BuffaloRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akwaaba': {
      id: '/akwaaba'
      path: '/akwaaba'
      fullPath: '/akwaaba'
      preLoaderRoute: typeof AkwaabaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colobus/': {
      id: '/colobus/'
      path: '/'
      fullPath: '/colobus/'
      preLoaderRoute: typeof ColobusIndexRouteImport
      parentRoute: typeof ColobusRouteRoute
    }
    '/buffalo/': {
      id: '/buffalo/'
      path: '/'
      fullPath: '/buffalo/'
      preLoaderRoute: typeof BuffaloIndexRouteImport
      parentRoute: typeof BuffaloRouteRoute
    }
    '/akwaaba/': {
      id: '/akwaaba/'
      path: '/'
      fullPath: '/akwaaba/'
      preLoaderRoute: typeof AkwaabaIndexRouteImport
      parentRoute: typeof AkwaabaRouteRoute
    }
    '/colobus/current-year-planting': {
      id: '/colobus/current-year-planting'
      path: '/current-year-planting'
      fullPath: '/colobus/current-year-planting'
      preLoaderRoute: typeof ColobusCurrentYearPlantingRouteImport
      parentRoute: typeof ColobusRouteRoute
    }
    '/buffalo/current-year-planting': {
      id: '/buffalo/current-year-planting'
      path: '/current-year-planting'
      fullPath: '/buffalo/current-year-planting'
      preLoaderRoute: typeof BuffaloCurrentYearPlantingRouteImport
      parentRoute: typeof BuffaloRouteRoute
    }
    '/akwaaba/current-year-planting': {
      id: '/akwaaba/current-year-planting'
      path: '/current-year-planting'
      fullPath: '/akwaaba/current-year-planting'
      preLoaderRoute: typeof AkwaabaCurrentYearPlantingRouteImport
      parentRoute: typeof AkwaabaRouteRoute
    }
  }
}

interface AkwaabaRouteRouteChildren {
  AkwaabaCurrentYearPlantingRoute: typeof AkwaabaCurrentYearPlantingRoute
  AkwaabaIndexRoute: typeof AkwaabaIndexRoute
}

const AkwaabaRouteRouteChildren: AkwaabaRouteRouteChildren = {
  AkwaabaCurrentYearPlantingRoute: AkwaabaCurrentYearPlantingRoute,
  AkwaabaIndexRoute: AkwaabaIndexRoute,
}

const AkwaabaRouteRouteWithChildren = AkwaabaRouteRoute._addFileChildren(
  AkwaabaRouteRouteChildren,
)

interface BuffaloRouteRouteChildren {
  BuffaloCurrentYearPlantingRoute: typeof BuffaloCurrentYearPlantingRoute
  BuffaloIndexRoute: typeof BuffaloIndexRoute
}

const BuffaloRouteRouteChildren: BuffaloRouteRouteChildren = {
  BuffaloCurrentYearPlantingRoute: BuffaloCurrentYearPlantingRoute,
  BuffaloIndexRoute: BuffaloIndexRoute,
}

const BuffaloRouteRouteWithChildren = BuffaloRouteRoute._addFileChildren(
  BuffaloRouteRouteChildren,
)

interface ColobusRouteRouteChildren {
  ColobusCurrentYearPlantingRoute: typeof ColobusCurrentYearPlantingRoute
  ColobusIndexRoute: typeof ColobusIndexRoute
}

const ColobusRouteRouteChildren: ColobusRouteRouteChildren = {
  ColobusCurrentYearPlantingRoute: ColobusCurrentYearPlantingRoute,
  ColobusIndexRoute: ColobusIndexRoute,
}

const ColobusRouteRouteWithChildren = ColobusRouteRoute._addFileChildren(
  ColobusRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkwaabaRouteRoute: AkwaabaRouteRouteWithChildren,
  BuffaloRouteRoute: BuffaloRouteRouteWithChildren,
  ColobusRouteRoute: ColobusRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
