/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AkwaabaRouteRouteImport } from './routes/akwaaba/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColobusIndexRouteImport } from './routes/colobus/index'
import { Route as BuffaloIndexRouteImport } from './routes/buffalo/index'
import { Route as AkwaabaIndexRouteImport } from './routes/akwaaba/index'

const AkwaabaRouteRoute = AkwaabaRouteRouteImport.update({
  id: '/akwaaba',
  path: '/akwaaba',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColobusIndexRoute = ColobusIndexRouteImport.update({
  id: '/colobus/',
  path: '/colobus/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuffaloIndexRoute = BuffaloIndexRouteImport.update({
  id: '/buffalo/',
  path: '/buffalo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AkwaabaIndexRoute = AkwaabaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AkwaabaRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/akwaaba': typeof AkwaabaRouteRouteWithChildren
  '/akwaaba/': typeof AkwaabaIndexRoute
  '/buffalo/': typeof BuffaloIndexRoute
  '/colobus/': typeof ColobusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/akwaaba': typeof AkwaabaIndexRoute
  '/buffalo': typeof BuffaloIndexRoute
  '/colobus': typeof ColobusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/akwaaba': typeof AkwaabaRouteRouteWithChildren
  '/akwaaba/': typeof AkwaabaIndexRoute
  '/buffalo/': typeof BuffaloIndexRoute
  '/colobus/': typeof ColobusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/akwaaba' | '/akwaaba/' | '/buffalo/' | '/colobus/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/akwaaba' | '/buffalo' | '/colobus'
  id: '__root__' | '/' | '/akwaaba' | '/akwaaba/' | '/buffalo/' | '/colobus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AkwaabaRouteRoute: typeof AkwaabaRouteRouteWithChildren
  BuffaloIndexRoute: typeof BuffaloIndexRoute
  ColobusIndexRoute: typeof ColobusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/akwaaba': {
      id: '/akwaaba'
      path: '/akwaaba'
      fullPath: '/akwaaba'
      preLoaderRoute: typeof AkwaabaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colobus/': {
      id: '/colobus/'
      path: '/colobus'
      fullPath: '/colobus/'
      preLoaderRoute: typeof ColobusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buffalo/': {
      id: '/buffalo/'
      path: '/buffalo'
      fullPath: '/buffalo/'
      preLoaderRoute: typeof BuffaloIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akwaaba/': {
      id: '/akwaaba/'
      path: '/'
      fullPath: '/akwaaba/'
      preLoaderRoute: typeof AkwaabaIndexRouteImport
      parentRoute: typeof AkwaabaRouteRoute
    }
  }
}

interface AkwaabaRouteRouteChildren {
  AkwaabaIndexRoute: typeof AkwaabaIndexRoute
}

const AkwaabaRouteRouteChildren: AkwaabaRouteRouteChildren = {
  AkwaabaIndexRoute: AkwaabaIndexRoute,
}

const AkwaabaRouteRouteWithChildren = AkwaabaRouteRoute._addFileChildren(
  AkwaabaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AkwaabaRouteRoute: AkwaabaRouteRouteWithChildren,
  BuffaloIndexRoute: BuffaloIndexRoute,
  ColobusIndexRoute: ColobusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
